[package]
name = "image-gallery-picker"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = "0.10"
gdk-pixbuf = "0.21.5"
async-channel = "2.5.0"
walkdir = "2.5.0"
glib = "0.21.5"
rayon = "1.11.0"
